# Generated by Django 5.0.2 on 2024-02-24 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstAuthorName', models.CharField(max_length=250, verbose_name='Имя автора')),
                ('lastAuthorName', models.CharField(max_length=250, verbose_name='Фамилия автора')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstOwnerName', models.CharField(max_length=250, verbose_name='Имя владельца')),
                ('lastOwnerName', models.CharField(max_length=250, verbose_name='Фамилия владельца')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to='board.author', verbose_name='Автор книги')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='board.owner', verbose_name='Владелец книги')),
            ],
        ),
    ]
